"""Hill Mixture MMM - Bayesian Marketing Mix Modeling with Mixture of Hill Curves."""

from .data import DGP_CONFIGS, DGPConfig, compute_prior_config, generate_data
from .benchmark import (
    BenchmarkCaseResult,
    BenchmarkRunConfig,
    BenchmarkThresholds,
    ComparisonThresholds,
    assert_case_passes,
    assert_comparison_passes,
    case_summary,
    compare_case_results,
    evaluate_case_diagnostic_status,
    evaluate_diagnostic_summary,
    plot_case_comparison,
    plot_observed_vs_predictive,
    plot_response_curves,
    resolve_case_artifact_dir,
    resolve_comparison_artifact_dir,
    run_real_benchmark_case,
    run_synthetic_benchmark_case,
    save_case_artifacts,
)
from .inference import (
    compute_convergence_diagnostics,
    compute_label_invariant_diagnostics,
    compute_loo,
    compute_predictions,
    compute_predictive_metrics,
    compute_waic,
    run_inference,
)
from .metrics import (
    compute_across_seed_component_stability,
    compute_component_set_alignment,
    compute_delta_loo,
    compute_effective_k,
    compute_latent_recovery,
    compute_permutation_invariant_component_recovery,
    compute_parameter_recovery,
    summarize_component_posterior,
)
from .models import (
    model_hill_mixture_hierarchical_reparam,
    model_single_hill,
)
from .transforms import adstock_geometric, hill, hill_matrix

__version__ = "0.1.0"

__all__ = [
    "DGPConfig",
    "DGP_CONFIGS",
    "generate_data",
    "compute_prior_config",
    "BenchmarkCaseResult",
    "BenchmarkRunConfig",
    "BenchmarkThresholds",
    "ComparisonThresholds",
    "run_synthetic_benchmark_case",
    "run_real_benchmark_case",
    "assert_case_passes",
    "assert_comparison_passes",
    "compare_case_results",
    "case_summary",
    "evaluate_case_diagnostic_status",
    "evaluate_diagnostic_summary",
    "plot_observed_vs_predictive",
    "plot_response_curves",
    "plot_case_comparison",
    "resolve_case_artifact_dir",
    "resolve_comparison_artifact_dir",
    "save_case_artifacts",
    "run_inference",
    "compute_convergence_diagnostics",
    "compute_label_invariant_diagnostics",
    "compute_loo",
    "compute_predictions",
    "compute_predictive_metrics",
    "compute_waic",
    "compute_delta_loo",
    "compute_effective_k",
    "compute_latent_recovery",
    "compute_component_set_alignment",
    "compute_permutation_invariant_component_recovery",
    "compute_across_seed_component_stability",
    "compute_parameter_recovery",
    "summarize_component_posterior",
    "model_single_hill",
    "model_hill_mixture_hierarchical_reparam",
    "adstock_geometric",
    "hill",
    "hill_matrix",
]
